# Generated by Django 5.0.1 on 2024-02-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='Service',
        ),
    ]
