# Generated by Django 5.0.1 on 2024-03-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Gallerys',
        ),
    ]
