# Generated by Django 5.0.1 on 2024-03-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_rename_galleryimage_gallerys_gimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallerys',
        ),
    ]
