# Generated by Django 5.0.1 on 2024-03-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
