# Generated by Django 5.0.1 on 2024-03-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_pcategory_shopdetials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopdetials',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shopdetials',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shopdetials',
            name='materialType',
        ),
        migrations.RemoveField(
            model_name='shopdetials',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shopdetials',
            name='qty',
        ),
    ]
